services:
  db:
    container_name: pixelfed-ci-db
    restart: "no"
    volumes:
      - pixelfed-ci-database:/var/lib/mysql

  redis:
    container_name: pixelfed-ci-redis
    restart: "no"
    volumes:
      - pixelfed-ci-redis:/data

  pixelfed:
    image: ${PIXELFED_IMAGE:-mochirii-pixelfed:production-check}
    container_name: pixelfed-ci-app
    restart: "no"
    ports: !reset []
    volumes:
      - pixelfed-ci-storage:/var/www/html/storage

  horizon:
    image: ${PIXELFED_IMAGE:-mochirii-pixelfed:production-check}
    container_name: pixelfed-ci-horizon
    restart: "no"
    volumes:
      - pixelfed-ci-storage:/var/www/html/storage

  scheduler:
    image: ${PIXELFED_IMAGE:-mochirii-pixelfed:production-check}
    container_name: pixelfed-ci-scheduler
    restart: "no"
    volumes:
      - pixelfed-ci-storage:/var/www/html/storage

volumes:
  pixelfed-ci-database:
  pixelfed-ci-redis:
  pixelfed-ci-storage:
